version: "3"
services:
  dremio:
    image: dremio/dremio-oss:latest
    container_name: dremio_local
    hostname: dremio
    networks:
        - dremio_net
    ports:
      - "9047:9047"   # UI (HTTP)
      - "31010:31010" # ODBC/JDBC clients
      - "2181:2181"   # ZooKeeper
      - "45678:45678" # Inter-node communication

networks:
    dremio_net:
      